2020-05-07 02:07:15,212 ERROR: Exception on / [GET] [in c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Lisa\salon\app\routes.py", line 23, in index
    masters = Master.query.filter(type(user_id) == int).paginate(
NameError: name 'user_id' is not defined
2020-05-07 02:08:33,558 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 02:09:22,255 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 02:11:11,299 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 17:25:08,770 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 17:25:35,266 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-07 17:25:56,327 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:51]
2020-05-08 11:28:09,381 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 11:28:23,818 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 11:31:40,946 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 11:33:29,453 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 11:34:51,661 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 11:39:06,733 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 11:39:17,651 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 11:55:36,225 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 11:55:39,757 ERROR: Exception on / [GET] [in c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Lisa\salon\app\routes.py", line 31, in index
    prev_url=prev_url)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lisa\salon\app\templates\index.html", line 5, in template
    <h1>{{ _(Our masters) }}</h1>
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'masters'
2020-05-08 11:56:14,780 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 13:06:52,614 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 13:08:16,831 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 13:21:01,714 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 13:25:07,402 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 13:25:51,639 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 14:47:55,291 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
2020-05-08 14:48:01,925 ERROR: Exception on /followers/david [GET] [in c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Lisa\salon\app\routes.py", line 163, in followers
    next_url=next_url, prev_url=prev_url)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lisa\salon\app\templates\follow_ers_ings.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Lisa\salon\app\templates\base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Lisa\salon\app\templates\follow_ers_ings.html", line 7, in block "app_content"
    {% include '_folls.html' %}
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\lisa\salon\myvenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Lisa\salon\app\templates\_folls.html", line 19, in template
    <p><a href="{{ url_for('unfollow', username=foll.username) }}">{{ _('Unfollow') }}</a></p>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.
2020-05-08 14:48:56,952 INFO: Salon startup [in C:\Users\Lisa\salon\app\__init__.py:52]
